### PR TITLE
Clean up HTML, CSS, JS

### PR DESCRIPTION
**Pull request by cam-vanorman**
I haven't merged your changes with mine yet as it looks like js/html has been updated in the last couple of weeks. I can repull if you'd like for me to merge first.

### CODE REVIEW

**Comment by arielkirkwood** [comment]
@cam-vanorman Are you familiar with [rebasing](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages)? Your pull request could use a bit of cleanup :) (specifically in terms of removing the merge commits)

**Comment by arielkirkwood** [comment]
I'd love to see this PR merged - it takes care of what I did in #11 with a more precise CSS selector.

**Comment by Valadian** [comment]
wow, that index.html is a nasty merge. Was going to try to get this before work.. but will need more time. Will take a pass after.

**Comment by cam-vanorman** [comment]
Yeah, I'll admit, I'm pretty bad with git at the moment, specifically with merging in changes (rebasing). I can take a crack at it later tonight since yeah that index merge is nasty.

**Comment by Valadian** [comment]
I just want to make sure I don't miss any of your changes. I am working
overtime tonight...  But will probably be able to get to it later tonight.

**Comment by Valadian** [comment]
That was just terribly stupid ugly.

I also realized it is nearly impossible to do hard merges while babysitting a border collie puppy.

All done now, onward!

**Comment by cam-vanorman** [comment]
You're a scholar and a gentleman, thank you for merging!

**Pull request merged**
